title: "Welcome to my blog"
date: 2018-04-20
author: fran6ien
email: gnefo2012@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Learning github

# social links
github_username:  fran6ien
facebook_username: francien

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
